# Numerical Python

In [10]:
import numpy as np

# Ndarray

arr1=np.array([1,2,3,4,5])

print(type(arr1))
print(f"Dimension of array is {arr1.ndim}")

# 2d Array

arr2= np.array([[1,2,3,], # row 1
                [4,5,6]]) # row 2

print(f"Dimension of array is {arr2.ndim}")


# 3d array

arr3= np.array([
               #1st floor
               [ [1,2,3], # row 1
                [4,5,6]] ,  # row 2
               # 2nd floo
               
               [ [1,2,3,], # row 1
                [4,5,6]], # row 2
               
               #3rd floor
               [ [1,2,3,], # row 1
                [4,5,6]]] # row 2 
               )

print(f"Dimension of array is {arr3.ndim}")


<class 'numpy.ndarray'>
Dimension of array is 1
Dimension of array is 2
Dimension of array is 3


## Attribute of Array

In [ ]:
# dimension
print("Dimensions")
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

#shape
print("")
print("Shape")
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

# Data type
print("")
print("Data Type")
print(arr1.dtype) # row 5 col 0
print(arr2.dtype) # row 2 column 3
print(arr3.dtype) # floor 3 row 2 col 3

#Size
print("")
print("Size")
print(arr1.size)
print(arr2.size)
print(arr3.size)



Dimensions
1
2
3

Shape
(5,)
(2, 3)
(3, 2, 3)

Data Type
int64
int64
int64

Size
5
6
18


# ndarray data type

In [12]:
arr = np.array([1,2,3])

print(arr.dtype)

arr = np.array([1.5,2.4,3.2])
print(arr.dtype)

int64
float64


In [13]:
arr = np.array([1,2,3.2])
# upcasted to float
print(arr.dtype)

#upcasted to string
arr = np.array([1,2,3.2,'hello'])
print(arr.dtype)


arr = np.array([1,True,3.25,'hello',])
print(arr.dtype)

float64
<U32
<U32


# selecting a data type for an array

In [14]:
arr = np.array([1,2,300],dtype=np.int16)
print(arr.dtype)
print(arr)


arr = arr.astype(np.int32)
print(arr.dtype)


#error
arr = np.array([1,2,3.2,'hello'],dtype=np.float64)

int16
[  1   2 300]
int32


ValueError: could not convert string to float: 'hello'

# ndarray creation from existing data

In [15]:
#list

lst = [10,20,30,40 , 40.5]

arr = np.array(lst, dtype=np.int32)

# print(arr)
# print(type(arr))
# print(arr.dtype)


mixed_lst = [10, True , 'Hello' ]

arr = np.array(mixed_lst)

# print(arr)
# print(type(arr))
# print(arr.dtype)


matrix = [ [1,2,3], # row1
           [4,5,6] #row2
                ]

arr = np.array(matrix)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [16]:
# tuple

#tuple

tpl = (10,20,30)

arr = np.array(tpl,dtype=np.int32)
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

int32
[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1


In [17]:
#set

st = { 1, 2, 3 }

arr = np.array(list(st))
# print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int16
(3,)
1


In [18]:
# dictionary

dc = { 'a' : 10 , 'b' : 20 , 'c' :30 }

keys = dc.keys()
values = dc.values()
items = dc.items()

In [19]:
#keys to ndarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


In [20]:
#values to ndarray
arr = np.array(list(values))
print(arr)
arr = arr.astype(np.int16)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1
3


In [21]:
#items to ndarray
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


# Creating ndarray from scratch

In [22]:
# np.zeros

arr = np.zeros((2,3),dtype=np.int8)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

arr = np.zeros_like(arr3) ## arr3 shape same
print(arr)
print(arr.shape)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(3, 2, 3)


In [23]:
#np.ones

arr = np.ones((3,4,3),dtype=np.int8)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)


arr = np.ones_like(arr3) ## arr3 shape same
print(arr)
print(arr.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


# array creation with random values

In [24]:
# np.random.rand(shape)

arr = np.random.rand(2,3) # 0 ->1

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0.17793832 0.06467442 0.82035541]
 [0.53483514 0.38614775 0.28613235]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [25]:
# np.random.randint(start,end, shape)

arr = np.random.randint(1,10 , (2,3))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[9 9 1]
 [4 3 7]]
<class 'numpy.ndarray'>
int32
(2, 3)
2
6


In [26]:
# np.random.uniform(start,end, shape)

arr = np.random.uniform(50,100, (3,3,4))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[56.84312357 67.9263059  72.33987378 63.80223133]
  [78.46214137 50.70821752 75.81021533 55.70368651]
  [91.99301848 55.00300603 76.71946994 78.26535021]]

 [[57.50019008 50.45107428 60.00103404 58.21922218]
  [60.94308255 66.97886142 66.8218881  98.54800652]
  [71.21282657 87.31692516 70.99530741 55.25083115]]

 [[58.95912576 62.91447396 67.57317205 80.18101507]
  [62.04030033 76.39779958 61.98703929 71.23131696]
  [64.15721155 84.93728326 74.44616257 59.80054899]]]
<class 'numpy.ndarray'>
float64
(3, 3, 4)
3
36


# array creation with range functions

In [27]:
# np.arange(first , end , step ) -> similar to range function

arr = np.arange(1 , 10 ,1 )
mat = arr.reshape(3,3)

print(arr)
print(mat)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [28]:
# np.linspace(start , end(included) , koita)

arr = np.linspace(0, 4 ,6)


print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[0.  0.8 1.6 2.4 3.2 4. ]
<class 'numpy.ndarray'>
float64
(6,)
1
6


In [30]:
# np.logspace(start , end(included) , koita )

arr = np.logspace(0 , 4 ,6, base =2)

print(arr)

[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


# Creating Matrix for Linear Algebra

In [31]:
diagonal_matrix = np.diag([1,2,3,4])

print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [32]:
# identity matrix

identity_mat = np.eye(4)
# print(identity_mat)
# print(identity_mat.shape)


# np.eye(row , column,k)

mat = np.eye(3,4)
print(mat)

mat = np.eye(3,4,1)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Indexing and Slicing

In [33]:
#indexing

print(arr1)
print(arr2)

# arr1[2] = 100

# print(arr1)
arr2[0][2]= 100

print(arr2)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[  1   2 100]
 [  4   5   6]]


In [34]:
#slicing
#1d = arr[start:end:step]

arr1_mod = arr1[1:4].copy()
arr1[1] = 2


arr1_mod[2] = 200
print(arr1_mod)
print(arr1)

[  2   3 200]
[1 2 3 4 5]


In [40]:
#2d slicing
# arr[ row_start : row_end : step , column_start : column_end : step ]

print(arr2)
print("")
#getting a row

row_0 = arr2[0:1 ,]

row_1= arr2[1: , ]

print(row_0)
print(row_1)
print("")

#getting a column

col_0 = arr2[:: ,0:1]
col_1 = arr2[::,1:2]

print(col_0)
print("")
print(col_1)

#getting a portion


portion = arr2[:: , 0:2]
print("")
print(portion)

[[  1   2 100]
 [  4   5   6]]

[[  1   2 100]]
[[4 5 6]]

[[1]
 [4]]

[[2]
 [5]]

[[1 2]
 [4 5]]
