# Numerical Python - part 2

## nd-array manipulation

In [1]:
import numpy as np

arr = np.random.randint(1,100,size=(10,5)) # sample -10 , feature -5
arr.shape

(10, 5)

In [9]:
# shape change (example change it like 10 row will be 5 col and 5 col will be 10 row)

b=arr.reshape(5,10)

print(b.shape)

# shape should be valid 10*5=50 data can not be converted into 3*5=15 data

print(b.ndim)
print(b)

(5, 10)
2
[[38 88 68 52 42 77 63 99  8 77]
 [67 15 78 64 49 57 14 79 58 88]
 [73 67 21 98 65  9 96 52 43 39]
 [71 57  2  9 33 39 16 51 94 33]
 [63 17 75 63 80 34 97 79  4 38]]


In [10]:
flatten = b.flatten()
print(flatten.ndim)
print(flatten)

1
[38 88 68 52 42 77 63 99  8 77 67 15 78 64 49 57 14 79 58 88 73 67 21 98
 65  9 96 52 43 39 71 57  2  9 33 39 16 51 94 33 63 17 75 63 80 34 97 79
  4 38]


In [ ]:
column_wise_flattening= np.ravel(b,order="F")
print(column_wise_flattening)

[38 67 73 71 63 88 15 67 57 17 68 78 21  2 75 52 64 98  9 63 42 49 65 33
 80 77 57  9 39 34 63 14 96 16 97 99 79 52 51 79  8 58 43 94  4 77 88 39
 33 38]


In [ ]:
a= np.random.randint(1,10,size=(2,3))

b= np.random.randint(20,30, size = (2,3))

print(a)
print(b)



[[8 9 4]
 [9 1 2]]
[[25 21 23]
 [29 29 26]]


In [ ]:
# Concatenate (row wise or column wise) shape same thakbe

con_row= np.concatenate((a,b),axis=0) # row wise column same thakbe hobe

print(con_row)

[[ 8  9  4]
 [ 9  1  2]
 [25 21 23]
 [29 29 26]]


In [ ]:
# Concatenate (row wise or column wise)

con_col= np.concatenate((a,b),axis=1) # col wise row same thakbe hobe

print(con_col)

[[ 8  9  4 25 21 23]
 [ 9  1  2 29 29 26]]


In [16]:
# error

# row wise concetanate korar shomoi column same thakbe
# col wise concat korar shomoi row ta same thakte hobe

x = np.random.randint(1 ,10 , size =(2,3))
y = np.random.randint(1 ,10 , size =(1,3))

r = np.concatenate((x,y),axis =0 )
r = np.concatenate((x,y),axis =1 )
print(r)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [17]:
# transpose

mat = np.array([[10,20,30],
                [30,40,50]
               ])


transpose = mat.T

print(transpose)

[[10 30]
 [20 40]
 [30 50]]


In [20]:
# array split

a = np.random.randint(1 ,10 , size =(10,))
print(a)
splitted_array = np.array_split(a,3)

print(splitted_array)

# split -> equal division
splitted_array = np.split(a,3) #---> error


[4 5 3 3 8 3 8 9 1 4]
[array([4, 5, 3, 3], dtype=int32), array([8, 3, 8], dtype=int32), array([9, 1, 4], dtype=int32)]


ValueError: array split does not result in an equal division

## Arithmetical & Mathematical

In [ ]:
x = np.array([ 10 , 8 , 30 , 100 ])
y = np.array([ 2 , 3 ,4  ,5 ])

add = np.add(x,y)
print(add)

sub = x-y
print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

remainder = x % y

print(remainder)

# faster for vectorization


[ 12  11  34 105]
[ 8  5 26 95]
[ 20  24 120 500]
[ 5.          2.66666667  7.5        20.        ]
[0 2 2 0]


In [22]:
# mathematical function

# trigonometry

# sin , cos , tan takes values in radian

sin_val = np.sin(x)
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

deg_con = np.rad2deg(x)
print(deg_con)

# deg2rad

[-0.54402111  0.98935825 -0.98803162 -0.50636564]
[-0.83907153 -0.14550003  0.15425145  0.86231887]
[ 572.95779513  458.3662361  1718.87338539 5729.57795131]


In [23]:
#log

x = np.array([ 10 , 8 , 16 , 100 ])
base_10_log_val = np.log10(x)
print(base_10_log_val)


two_diye_bhag = np.log2(x)
print(two_diye_bhag)

sqrt= np.sqrt(x)
print(sqrt)

[1.         0.90308999 1.20411998 2.        ]
[3.32192809 3.         4.         6.64385619]
[ 3.16227766  2.82842712  4.         10.        ]


In [24]:
# different
s = np.sum(x)
print(s)

#prefix sum
cumul =np.cumulative_sum(x)
print(cumul)

134
[ 10  18  34 134]


## Logical Function

In [2]:
# comparison - >,< , >= ,<= , == , !=
import numpy as np

x = np.array([ 10 , 8 , 16 , 100 ])
y = np.array([ 2 , 3 ,16  ,5 ])

greater_than = x>y

print(greater_than)

equal = x==y

print(equal)

# all () -> shob true kina
# any() -> jekono ekta true ase kina

print(np.all(greater_than))

print(np.any(equal))

[ True  True False  True]
[False False  True False]
False
True


## Sorting

In [4]:
#inplace
x = np.array([ 10 , 8 , 16 , 100 ])

z = x.copy()

print(z)

z.sort()

print(z)

[ 10   8  16 100]
[  8  10  16 100]


In [5]:
# copy sorting
print(x)
sort_arr = np.sort(x)

print(sort_arr)

print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [ ]:
# 2d array sorting
mat = np.array([[10,3,5],[8,4,9]])

# horizon axis = 1
# Vertical axis = 0

hor_sort = np.sort(mat,axis=1)
print(hor_sort)

vert_sort = np.sort(mat,axis=0)
print(vert_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


## Searching

In [7]:
print(x)

[ 10   8  16 100]


In [8]:
# np.where( condition , x , y ) if true x , otherwise replace with y

index = np.where(x==8) # returns index
print(index)

arr = np.where(x>8,x,0) # returns array
print(arr)

(array([1]),)
[ 10   0  16 100]


In [9]:
print(mat)

[[10  3  5]
 [ 8  4  9]]


In [10]:
index = np.where(mat>8) # returns index
print(index)

arr = np.where(mat>8,mat,0) # returns array
print(arr)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [11]:
x = np.array([ 10,100 , 8 , 16 , 100 ])

maximum_value_indx = np.argmax(x)
minimum_value_indx = np.argmin(x)

print(maximum_value_indx)
print(minimum_value_indx)

1
2


## counting in ndarray

In [15]:
a = np.random.randint(1 ,100 , size =(100,))
print(a)

[22  1 22  6 62 11 32  3 92 73 48 32 73 80 42 62 37 99 17 59  4 82 63 24
 67 16 94 29 75  5 46 81 91 57 31 24 19 47 97  7 79 53 35 85 91 24 85  8
 94 95 77 85 49 90 75  5 73 91 64 24 42 82 65 26 48 84 65  3 66 26 47 33
 84 48 69 71 32 13 70 65 34 59 48 85 32 76 97 18 77 22 95 55 26 95 88 98
  4 56 37 48]


In [18]:
value_great_than_60 = np.count_nonzero(a>1)
print(value_great_than_60)

99


In [17]:
unique_value,count = np.unique(a,return_counts=True)

print(unique_value)
print(count)

[ 1  3  4  5  6  7  8 11 13 16 17 18 19 22 24 26 29 31 32 33 34 35 37 42
 46 47 48 49 53 55 56 57 59 62 63 64 65 66 67 69 70 71 73 75 76 77 79 80
 81 82 84 85 88 90 91 92 94 95 97 98 99]
[1 2 2 2 1 1 1 1 1 1 1 1 1 3 4 3 1 1 4 1 1 1 2 2 1 2 5 1 1 1 1 1 2 2 1 1 3
 1 1 1 1 1 3 2 1 2 1 1 1 2 2 4 1 1 3 1 2 3 2 1 1]


## statistical function

## linear algebra