# Numerical Python - part 2

## nd-array manipulation

In [1]:
import numpy as np

arr = np.random.randint(1,100,size=(10,5)) # sample -10 , feature -5
arr.shape

(10, 5)

In [9]:
# shape change (example change it like 10 row will be 5 col and 5 col will be 10 row)

b=arr.reshape(5,10)

print(b.shape)

# shape should be valid 10*5=50 data can not be converted into 3*5=15 data

print(b.ndim)
print(b)

(5, 10)
2
[[38 88 68 52 42 77 63 99  8 77]
 [67 15 78 64 49 57 14 79 58 88]
 [73 67 21 98 65  9 96 52 43 39]
 [71 57  2  9 33 39 16 51 94 33]
 [63 17 75 63 80 34 97 79  4 38]]


In [10]:
flatten = b.flatten()
print(flatten.ndim)
print(flatten)

1
[38 88 68 52 42 77 63 99  8 77 67 15 78 64 49 57 14 79 58 88 73 67 21 98
 65  9 96 52 43 39 71 57  2  9 33 39 16 51 94 33 63 17 75 63 80 34 97 79
  4 38]


In [ ]:
column_wise_flattening= np.ravel(b,order="F")
print(column_wise_flattening)

[38 67 73 71 63 88 15 67 57 17 68 78 21  2 75 52 64 98  9 63 42 49 65 33
 80 77 57  9 39 34 63 14 96 16 97 99 79 52 51 79  8 58 43 94  4 77 88 39
 33 38]


In [ ]:
a= np.random.randint(1,10,size=(2,3))

b= np.random.randint(20,30, size = (2,3))

print(a)
print(b)



[[8 9 4]
 [9 1 2]]
[[25 21 23]
 [29 29 26]]


In [ ]:
# Concatenate (row wise or column wise) shape same thakbe

con_row= np.concatenate((a,b),axis=0) # row wise column same thakbe hobe

print(con_row)

[[ 8  9  4]
 [ 9  1  2]
 [25 21 23]
 [29 29 26]]


In [ ]:
# Concatenate (row wise or column wise)

con_col= np.concatenate((a,b),axis=1) # col wise row same thakbe hobe

print(con_col)

[[ 8  9  4 25 21 23]
 [ 9  1  2 29 29 26]]


In [16]:
# error

# row wise concetanate korar shomoi column same thakbe
# col wise concat korar shomoi row ta same thakte hobe

x = np.random.randint(1 ,10 , size =(2,3))
y = np.random.randint(1 ,10 , size =(1,3))

r = np.concatenate((x,y),axis =0 )
r = np.concatenate((x,y),axis =1 )
print(r)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [17]:
# transpose

mat = np.array([[10,20,30],
                [30,40,50]
               ])


transpose = mat.T

print(transpose)

[[10 30]
 [20 40]
 [30 50]]


In [20]:
# array split

a = np.random.randint(1 ,10 , size =(10,))
print(a)
splitted_array = np.array_split(a,3)

print(splitted_array)

# split -> equal division
splitted_array = np.split(a,3) #---> error


[4 5 3 3 8 3 8 9 1 4]
[array([4, 5, 3, 3], dtype=int32), array([8, 3, 8], dtype=int32), array([9, 1, 4], dtype=int32)]


ValueError: array split does not result in an equal division

## Arithmetical & Mathematical

## Logical Method

## Sorting

## Searching