# Numerical Python - part 2

## nd-array manipulation

In [1]:
import numpy as np

arr = np.random.randint(1,100,size=(10,5)) # sample -10 , feature -5
arr.shape

(10, 5)

In [9]:
# shape change (example change it like 10 row will be 5 col and 5 col will be 10 row)

b=arr.reshape(5,10)

print(b.shape)

# shape should be valid 10*5=50 data can not be converted into 3*5=15 data

print(b.ndim)
print(b)

(5, 10)
2
[[38 88 68 52 42 77 63 99  8 77]
 [67 15 78 64 49 57 14 79 58 88]
 [73 67 21 98 65  9 96 52 43 39]
 [71 57  2  9 33 39 16 51 94 33]
 [63 17 75 63 80 34 97 79  4 38]]


In [8]:
flatten = b.flatten()
print(flatten.ndim)

1


## Arithmetical & Mathematical

## Logical Method

## Sorting

## Searching